# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161227_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bintroduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='should_return',
            field=models.DateField(default=datetime.datetime(2017, 6, 1, 2, 10, 12, 475460, tzinfo=utc), verbose_name='应还日期'),
        ),
    ]
